// Mocks generated by Mockito 5.3.2 from annotations
// in my_tmdb/test/features/popular_movies/popular_movies_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dfunc/dfunc.dart' as _i2;
import 'package:fast_immutable_collections/fast_immutable_collections.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:my_tmdb/src/features/popular_movies/popular_movie.dart' as _i6;
import 'package:my_tmdb/src/features/popular_movies/src/popular_movies_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PopularMoviesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularMoviesRepository extends _i1.Mock
    implements _i3.PopularMoviesRepository {
  MockPopularMoviesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<Exception, _i5.IList<_i6.PopularMovie>>>
      fetchPopularMovies() => (super.noSuchMethod(
            Invocation.method(
              #fetchPopularMovies,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<Exception, _i5.IList<_i6.PopularMovie>>>.value(
                _FakeEither_0<Exception, _i5.IList<_i6.PopularMovie>>(
              this,
              Invocation.method(
                #fetchPopularMovies,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<Exception, _i5.IList<_i6.PopularMovie>>>);
}
