include: package:mews_pedantic/analysis_options.yaml

linter:
  rules:
    - prefer_relative_imports

analyzer:
  errors:
    always_use_package_imports: ignore
    avoid_relative_lib_imports: ignore

  exclude:
    - "**/di.config.dart"
    - "**/*.gr.dart"

dart_code_metrics:
  rules:
    avoid-banned-imports:
      severity: error
      entries:
        - paths: [".*/models/.+\\.dart"]
          deny: [".*/(data|services|widgets|screens|ui|l10n)/.*"]
          message: "Do not import data|services|widgets|screens|ui|l10n from models"

        - paths: [".*/data/.+\\.dart"]
          deny: [".*/(services|widgets|screens|ui)/.*"]
          message: "Do not import services|widgets|screens|ui from data"

        - paths: [".*/services/.+\\.dart"]
          deny: [".*/(widgets|screens|ui|l10n)/.*"]
          message: "Do not import widgets|screens|ui|l10n from services"

        - paths: [".*/ui/.+\\.dart"]
          deny: [".*/features/.*"]
          message: "Do not import features from ui"
