// Mocks generated by Mockito 5.4.4 from annotations
// in my_tmdb/test/features/search/data/search_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:my_tmdb/features/search/data/search_api_client.dart' as _i3;
import 'package:my_tmdb/utils/paginated_response_dto.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePaginatedResponseDto_0<T> extends _i1.SmartFake
    implements _i2.PaginatedResponseDto<T> {
  _FakePaginatedResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SearchApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchApiClient extends _i1.Mock implements _i3.SearchApiClient {
  MockSearchApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PaginatedResponseDto<_i3.SearchMoviesResultDto>> searchMovies({
    required String? apiKey,
    required String? query,
    required int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [],
          {
            #apiKey: apiKey,
            #query: query,
            #page: page,
          },
        ),
        returnValue: _i4
            .Future<_i2.PaginatedResponseDto<_i3.SearchMoviesResultDto>>.value(
            _FakePaginatedResponseDto_0<_i3.SearchMoviesResultDto>(
          this,
          Invocation.method(
            #searchMovies,
            [],
            {
              #apiKey: apiKey,
              #query: query,
              #page: page,
            },
          ),
        )),
      ) as _i4.Future<_i2.PaginatedResponseDto<_i3.SearchMoviesResultDto>>);

  @override
  _i4.Future<
      _i2.PaginatedResponseDto<_i3.SearchTvShowsResultDto>> searchTvShows({
    required String? apiKey,
    required String? query,
    required int? page,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvShows,
          [],
          {
            #apiKey: apiKey,
            #query: query,
            #page: page,
          },
        ),
        returnValue: _i4
            .Future<_i2.PaginatedResponseDto<_i3.SearchTvShowsResultDto>>.value(
            _FakePaginatedResponseDto_0<_i3.SearchTvShowsResultDto>(
          this,
          Invocation.method(
            #searchTvShows,
            [],
            {
              #apiKey: apiKey,
              #query: query,
              #page: page,
            },
          ),
        )),
      ) as _i4.Future<_i2.PaginatedResponseDto<_i3.SearchTvShowsResultDto>>);
}
